version: "3.7"

services:
  caddy:
    container_name: gen-ai-n8n-builder-caddy
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - n8n
    volumes:
      - gen-ai-n8n-builder-caddy-data:/data
      - ${DATA_FOLDER}/caddy_config:/config
      - ${DATA_FOLDER}/caddy_config/Caddyfile:/etc/caddy/Caddyfile

  n8n:
    container_name: gen-ai-n8n-builder
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - 5678:5678
    environment:
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
    volumes:
      - gen-ai-n8n-builder-data:/home/node/.n8n
      - ${DATA_FOLDER}/local_files:/files
      
volumes:
  gen-ai-n8n-builder-caddy-data:
    name: gen-ai-n8n-builder-caddy-data
    driver: local
  gen-ai-n8n-builder-data:
    name: gen-ai-n8n-builder-data
    driver: local
