version: "3.7"

services:
  caddy:
    container_name: gen-ai-n8n-builder-caddy
    image: caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - n8n
    volumes:
      - gen-ai-n8n-builder-caddy-data:/data
      - ${DATA_FOLDER}/caddy_config:/config
      - ${DATA_FOLDER}/caddy_config/Caddyfile:/etc/caddy/Caddyfile
    networks:
      - gen-ai-n8n-builder-network

  n8n:
    container_name: gen-ai-n8n-builder
    image: docker.n8n.io/n8nio/n8n
    restart: always
    ports:
      - 5678:5678
    environment:
      - N8N_HOST=${SUBDOMAIN}.${DOMAIN_NAME}
      - N8N_PORT=5678
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://${SUBDOMAIN}.${DOMAIN_NAME}/
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - DB_TYPE=mongodb
      - DB_MONGODB_CONNECTION_URL=mongodb://mongodb:27017/n8n
    volumes:
      - gen-ai-n8n-builder-data:/home/node/.n8n
      - ${DATA_FOLDER}/local_files:/files
    depends_on:
      - mongodb
    networks:
      - gen-ai-n8n-builder-network

  mongodb:
    container_name: gen-ai-n8n-builder-mongodb
    image: mongo:6
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - gen-ai-n8n-builder-mongo-data:/data/db
    networks:
      - gen-ai-n8n-builder-network

  ollama:
    container_name: gen-ai-n8n-builder-ollama
    image: ollama/ollama
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ollama-models:/root/.ollama
    tty: true
    networks:
      - gen-ai-n8n-builder-network

volumes:
  gen-ai-n8n-builder-caddy-data:
    name: gen-ai-n8n-builder-caddy-data
    driver: local
  gen-ai-n8n-builder-data:
    name: gen-ai-n8n-builder-data
    driver: local
  gen-ai-n8n-builder-mongo-data:
    name: gen-ai-n8n-builder-mongo-data
    driver: local
  ollama-models:
    name: ollama-models
    driver: local

networks:
  gen-ai-n8n-builder-network:
    name: gen-ai-n8n-builder-network
    driver: bridge
