services:
  report-generator:
    build: .
    container_name: report-generator
    env_file:
      - .env
    volumes:
      - ./reports:/app/reports
    command: tail -f /dev/null
    restart: always
