services:
  jira-report-generator:
    container_name: jira-report-generator
    build: .
    env_file:
      - .env
    volumes:
      - ./reports:/app/reports
    command: tail -f /dev/null
    restart: always
