services:
  agritech-news-agent:
    container_name: agritech-news-agent
    build: .
    env_file:
      - .env
    volumes:
      - .:/app
    command: tail -f /dev/null
    restart: unless-stopped
    networks:
      - gen-ai-network

networks:
  gen-ai-network:
    external: true
